# Generated by Django 3.1.4 on 2020-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='device id')),
                ('device_name', models.CharField(default='', max_length=100, verbose_name='device name')),
                ('description', models.TextField(default='', verbose_name='device description')),
                ('position', models.CharField(max_length=15, unique=True, verbose_name='device position')),
            ],
        ),
    ]
